version: "3.9"
services:
    rabbitmq:
        hostname: 'dev-rabbitmq'
        image: rabbitmq:3.8.14-management
        container_name: 'project-rabbitmq'
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
        networks:
            - test-network

networks:
    test-network:
        driver: bridge