apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3


# $ kubectl create -f rc-definition.yml
# $ kubectl get replicationcontroller
# $ kubectl get pods 