apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
selector:
  matchLabels:
    type: front-end

# $ kubectl create -f replicaset-definition.yml
# $ kubectl get replicaset
# $ kubectl get pods 